### ISSUE TITLE
error when loading map

### ISSUE THREAD

**Issue by ghost** [LovelySanta/FactorioMod-MoreScience-ScienceCostTweakerExtension#1]
https://pastebin.com/neCSn5z7

**Comment by LovelySanta** [comment]
Hi,

Thanks for trying my mod out.

The log file you posted says the error from the migration file is caused by the ScienceCostTweaker mod, and not my extension. This error is in line with mexmer/ScienceCostTweakerM#8 and should be solved already when you update your mod.

Kind regards,
lovely_santa
